const int SCREEN_WIDTH = 1920;
const int SCREEN_HEIGHT = 1080;

const int PARTICLE_SIZE = 4;
const int PARTICLE_RADIUS = PARTICLE_SIZE / 2;
const int PARTICLE_RADIUS_SQRD = PARTICLE_RADIUS * PARTICLE_RADIUS;

const int PARTICLE_COLLISION_AREA_SQRD = PARTICLE_RADIUS_SQRD / 2;
