const int SCREEN_WIDTH = 640;
const int SCREEN_HEIGHT = 480;

const int PARTICLE_SIZE = 20;
const int PARTICLE_RADIUS = PARTICLE_SIZE / 2;
const int PARTICLE_RADIUS_SQRD = PARTICLE_RADIUS * PARTICLE_RADIUS;